// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */

(function() {
  var NanikaPlugin,
    __slice = [].slice;

  NanikaPlugin = this.NanikaPlugin;

  if (NanikaPlugin == null) {
    NanikaPlugin = {};
  }

  NanikaPlugin.ssp = {
    initialize: function(nanika) {
      return nanika.on('materialized', function() {
        nanika.ssp.on('script:raise', function(_arg) {
          var args, id;
          id = _arg[0], args = 2 <= _arg.length ? __slice.call(_arg, 1) : [];
          return nanika.request('any', {
            id: id,
            headers: args
          });
        });
        return nanika.ssp.on('script:halt', function() {
          return nanika.halt();
        });
      });
    }
  };

  this.NanikaPlugin = NanikaPlugin;

}).call(this);
