// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */

(function() {
  var NanikaPlugin;

  NanikaPlugin = this.NanikaPlugin;

  if (NanikaPlugin == null) {
    NanikaPlugin = {};
  }

  NanikaPlugin.version = {
    initialize: function(nanika) {
      return nanika.on('materialized', function() {
        return nanika.request('version', null, function(response_args, response) {
          if (response.status_line.code === 200 && response.status_line.version !== '3.0') {
            nanika.protocol_version = '2.6';
            nanika.resource.version = response.headers.header.Version;
            nanika.resource.name = response.headers.header.ID;
            nanika.resource.craftman = response.headers.header.Craftman;
            nanika.resource.craftmanw = response.headers.header.Craftman;
          } else {
            nanika.protocol_version = '3.0';
            nanika.request('version', null, function(response_args) {
              return nanika.resource.version = response_args.value;
            });
            nanika.request('name', null, function(response_args) {
              return nanika.resource.name = response_args.value;
            });
            nanika.request('craftman', null, function(response_args) {
              return nanika.resource.craftman = response_args.value;
            });
            nanika.request('craftmanw', null, function(response_args) {
              return nanika.resource.craftmanw = response_args.value;
            });
          }
          return nanika.emit('version.set');
        });
      });
    }
  };

  this.NanikaPlugin = NanikaPlugin;

}).call(this);
