// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */

(function() {
  var NanikaPlugin;

  NanikaPlugin = this.NanikaPlugin;

  if (NanikaPlugin == null) {
    NanikaPlugin = {};
  }

  NanikaPlugin.close = {
    initialize: function(nanika) {
      nanika.on('response.close', function(args, optionals) {
        var _ref;
        if (!((_ref = args.value) != null ? _ref.length : void 0)) {
          return nanika.halt('close', args, optionals);
        }
      });
      nanika.on('ssp.finish.close', function(args, optionals) {
        return nanika.halt('close', args, optionals);
      });
      nanika.on('response.closeall', function(args, optionals) {
        var _ref;
        if (!((_ref = args.value) != null ? _ref.length : void 0)) {
          return nanika.halt('close', args, optionals);
        }
      });
      nanika.on('ssp.finish.closeall', function(args, optionals) {
        return nanika.halt('closeall', args, optionals);
      });
      nanika.on('response.changing', function(args, optionals) {
        var _ref;
        if (!((_ref = args.value) != null ? _ref.length : void 0)) {
          return nanika.halt('changing', args, optionals);
        }
      });
      return nanika.on('ssp.finish.changing', function(args, optionals) {
        return nanika.halt('changing', args, optionals);
      });
    }
  };

  this.NanikaPlugin = NanikaPlugin;

}).call(this);
