// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */

(function() {
  var NanikaPlugin;

  NanikaPlugin = this.NanikaPlugin;

  if (NanikaPlugin == null) {
    NanikaPlugin = {};
  }

  NanikaPlugin.input = {
    initialize: function(nanika) {
      return nanika.on('materialized', function() {
        nanika.named.on('userinput', function(event) {
          if (event.content != null) {
            return nanika.request('userinput', {
              id: event.id,
              content: event.content
            });
          } else {
            return nanika.request('userinputcancel', {
              id: event.id,
              reason: 'close'
            });
          }
        });
        return nanika.named.on('communicateinput', function(event) {
          if (event.content != null) {
            return nanika.request('communicate', {
              sender: 'user',
              content: event.content
            });
          } else {
            return nanika.request('communicateinputcancel', {
              reason: 'cancel'
            });
          }
        });
      });
    }
  };

  this.NanikaPlugin = NanikaPlugin;

}).call(this);
