// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */

(function() {
  var NanikaPlugin;

  NanikaPlugin = this.NanikaPlugin;

  if (NanikaPlugin == null) {
    NanikaPlugin = {};
  }

  NanikaPlugin.notify_browser_info = {
    initialize: function(nanika) {
      var notifybrowserinfo;
      notifybrowserinfo = function() {
        var args, browser, browser_version, info, info2, null2empty, parser, v;
        parser = new UAParser();
        info = parser.getResult();
        info2 = useragent_parser.parse(info.ua);
        switch (info2.family) {
          case "ANTGalio":
          case "Demeter":
          case "Fluid":
          case "Fresco":
          case "Galeon":
          case "GranParadiso":
          case "Iris":
          case "Kazehakase":
          case "Lobo":
          case "NetNewsWire":
          case "Shiira":
          case "Sleipnir":
          case "Sunrise":
          case "Vienna":
          case "Vodafone":
          case "WebPilot":
          case "IBrowse":
          case "Orca":
          case "Space Bison":
          case "Stainless":
            browser_version = ((function() {
              var _i, _len, _ref, _results;
              _ref = [info2.v1, info2.v2, info2.v3];
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                v = _ref[_i];
                if (v != null) {
                  _results.push(v);
                }
              }
              return _results;
            })()).join('.');
            browser = {
              name: info2.family,
              version: browser_version
            };
            break;
          default:
            browser = info.browser;
        }
        null2empty = function(value) {
          if (value != null) {
            return value;
          } else {
            return '';
          }
        };
        args = {
          useragent: null2empty(info.ua),
          browser_name: null2empty(browser.name),
          browser_version: null2empty(browser.version),
          engine_name: null2empty(info.engine.name),
          engine_version: null2empty(info.engine.version),
          os_name: null2empty(info.os.name),
          os_version: null2empty(info.os.version),
          device_model: null2empty(info.device.name),
          device_type: null2empty(info.device.type),
          device_vendor: null2empty(info.device.vendor),
          cpu_arch: null2empty(info.cpu.architecture)
        };
        return nanika.request('notifybrowserinfo', args);
      };
      return nanika.on('version.set', notifybrowserinfo);
    }
  };

  this.NanikaPlugin = NanikaPlugin;

}).call(this);
