// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */

(function() {
  var NanikaPlugin;

  NanikaPlugin = this.NanikaPlugin;

  if (NanikaPlugin == null) {
    NanikaPlugin = {};
  }

  NanikaPlugin.mouse = {
    initialize: function(nanika) {
      return nanika.on('materialized', function() {
        var event_id, mouseevents, _i, _len, _results;
        mouseevents = ['mousedown', 'mousemove', 'mouseup', 'mouseclick', 'mousedblclick'];
        _results = [];
        for (_i = 0, _len = mouseevents.length; _i < _len; _i++) {
          event_id = mouseevents[_i];
          _results.push(nanika.named.on(event_id, (function(event_id) {
            return function(event) {
              return nanika.request(event_id, event);
            };
          })(event_id)));
        }
        return _results;
      });
    }
  };

  this.NanikaPlugin = NanikaPlugin;

}).call(this);
