// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */

(function() {
  var NanikaPlugin;

  NanikaPlugin = this.NanikaPlugin;

  if (NanikaPlugin == null) {
    NanikaPlugin = {};
  }

  NanikaPlugin.close = {
    initialize: function(nanika) {
      nanika.on('response.close', function(args) {
        if (!args.value) {
          return nanika.halt();
        }
      });
      nanika.on('ssp.finish.close', function() {
        return nanika.halt();
      });
      nanika.on('response.closeall', function(args) {
        if (!args.value) {
          return nanika.halt();
        }
      });
      nanika.on('ssp.finish.closeall', function() {
        return nanika.halt();
      });
      nanika.on('response.changing', function(args) {
        if (!args.value) {
          return nanika.halt();
        }
      });
      return nanika.on('ssp.finish.changing', function() {
        return nanika.halt();
      });
    }
  };

  this.NanikaPlugin = NanikaPlugin;

}).call(this);
